### ISSUE TITLE
Fails to minify when building

### ISSUE THREAD

**Issue by kevando** [fvdm/nodejs-searchitunes#20]
```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/searchitunes/searchitunes.js:12 
```

**Comment by fvdm** [comment]
Could you please provide more context? Like which tool are you using for minification, for what purpose, steps to reproduce the problem.

**Comment by fvdm** [comment]
As there is no response, I’m assuming the issue is resolved.
