### ISSUE TITLE
Correct averageScore

### ISSUE THREAD

**Issue by guar47** [fvdm/nodejs-searchitunes#23]
Hello! Thanks for the amazing lib for Apple Lookup.

Currently, if you use Apple lookup you get incorrect `averageUserRating`. I know it's not a problem of the package, but of Apple Itunes Lookup API. 
But maybe you know if there is a way to get correct UserRatings?
Right now they are rounded to 0.5.

Example: https://apps.apple.com/us/app/tangle-tower/id1437742603 - if you check it inside the Apple store you see 4.8 rating in US region.
If you ask Apple Lookup in the same region you get 5.0 score.

**Comment by fvdm** [comment]
This is something I also struggle with. I think the true rankings are only exposed in the [enterprise feed](https://affiliate.itunes.apple.com/resources/documentation/itunes-enterprise-partner-feed/).

**Comment by guar47** [comment]
@fvdm Thanks for the answer, interesting. I applied for Enterprise Partner Feed, but I doubt they give me access since my app is still in development and it's really small.

**Comment by guar47** [comment]
Yeah, as expected Apple rejected my application:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/13599412/76588552-450d1480-6522-11ea-86ef-61366d186d64.png">

**Comment by guar47** [comment]
Heh, it's funny, but it seems Apple fixed this. I got the correct ratings today. 
`averageUserRating": 4.65894000000000030325963962241075932979583740234375`

It seems Lookup API still return rounded ratings, but since you're using Search API they started to return normal ratings.

**Comment by fvdm** [comment]
Wow that's nice! And an oddly specific rating 😄

**Comment by guar47** [comment]
I think since it's solved I close the issue, thanks for the answers!

**Comment by fvdm** [comment]
I see it now also in the Lookup API: `averageUserRating: 4.82013` ([example](https://runkit.com/franklin/searchitunes-lookup-rating/2.0.0)).

Thanks for reporting back about this and good luck with your project!
